### ISSUE TITLE
this might help

### ISSUE THREAD

**Issue by ErikTheGrate** [katorly/Minecraft-Earth-Buildplate#2]
this website has reconstructions of all the buildplates, but only in web form.
https://craftersguide.stents.dev/
it also has the adventures but i dont know if youd want to build that too.

**Comment by katorly** [comment]
> this website has reconstructions of all the buildplates, but only in web form.
> https://craftersguide.stents.dev/
> it also has the adventures but i dont know if youd want to build that too.

Hello, thanks for letting me know that website!

To be honest, I was actually referring to the models in that website when I was making these schem templates.

**Comment by ErikTheGrate** [comment]
you are doing good work for us all.
